--- #YAML:1.0
name:                Object-Event
version:             0.6
abstract:            A class that provides an event callback interface
license:             perl
author:              
    - Robin Redeker <elmex@x-paste.de>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Scalar::Util:                  0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
